use_frameworks!

platform :ios, '8.0'

target 'WCNetKit_Example' do
  pod 'WCNetKit', :path => '../'
  
  target 'WCNetKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
